In [4]:
import sys
import warnings

sys.path.extend(["..\\", "..\\dataScripts"])
warnings.filterwarnings("ignore")

import torch
import numpy as np

from vector_database_fill import FaissLoader
from systemComponents import embedding_model, VectorDb
from data_utils import TextEmbedding, normalize_vectors, chunk_pdf_file_pages

Loading weights: 100%|██████████| 389/389 [00:00<00:00, 8648.60it/s]
XLMRobertaModel LOAD REPORT from: Snowflake/snowflake-arctic-embed-l-v2.0
Key                 | Status     |  | 
--------------------+------------+--+-
pooler.dense.bias   | UNEXPECTED |  | 
pooler.dense.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [5]:
torch.cuda.is_available()

True

**VECTOR EMBEDDINGS**

In [8]:
# Create some test to run them through embedding model
sample_docs = ["You actually have to finish what you started",
               "Where can i find the best coffee in the town?",
               "You can ground yoursef with time and people"]
print(sample_docs)

['You actually have to finish what you started', 'Where can i find the best coffee in the town?', 'You can ground yoursef with time and people']


In [9]:
# Getting embeddings
embeddings_result = embedding_model(sample_docs)
embeddings_result

Loading weights: 100%|██████████| 389/389 [00:00<00:00, 8443.00it/s]
XLMRobertaModel LOAD REPORT from: Snowflake/snowflake-arctic-embed-l-v2.0
Key                 | Status     |  | 
--------------------+------------+--+-
pooler.dense.weight | UNEXPECTED |  | 
pooler.dense.bias   | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


array([[ 0.04765934,  0.01154986,  0.00960557, ..., -0.04375187,
        -0.02504937,  0.01745657],
       [ 0.04095765,  0.08059901,  0.03644542, ...,  0.05954833,
        -0.01518148, -0.01304296],
       [ 0.04184049,  0.02391438,  0.0574786 , ..., -0.04356113,
        -0.01385259, -0.00134557]], shape=(3, 1024), dtype=float32)

In [12]:
# Check whether the norms equal to 1
norm_values = np.apply_along_axis(np.linalg.norm, arr = embeddings_result, axis = 1).tolist()
norm_values

[0.9999999403953552, 1.0, 1.0]

**PDF CHUNKING**

In [17]:
pdf_chunking = PdfChunkReader(pdf_path="C:\\main\\GitHub\\documentReviewSystem\\knowledge_data\\Think like a Scientist_ Physics-guided LLM Agent for Equation Discovery.pdf")

In [18]:
chunk_result = pdf_chunking.get_chunks()
chunk_result[:5]

['Think like a Scientist: Physics-guided LLM Agent for Equation Discovery\nJianke Yang1 Ohm Venkatachalam1 Mohammad Kianezhad 1 Sharvaree Vadgama1 Rose Yu1\nAbstract\nExplaining observed phenomena through sym-\nbolic, interpretable formulas is a fundamental\ngoal of science. Recently, large language mod-\nels (LLMs) have emerged as promising tools for\nsymbolic equation discovery, owing to their broad\ndomain knowledge and strong reasoning capabili-\nties. However, most existing LLM-based systems\ntry to guess equations directly from data, with-\nout modeling the multi-step reasoning process\nthat scientists often follow: first inferring phys-\nical properties such as symmetries, then using\nthese as priors to restrict the space of candidate\nequations. We introduceKeplerAgent, an agentic\nframework that explicitly follows this scientific\nreasoning process. The agent coordinates physics-\nbased tools to extract intermediate structure and\nuses these results to configure symbolic regre

In [19]:
print(f"Length of chunk list: {len(chunk_result)}")
print(f"Chunk lengths: {list(map(lambda lst: len(lst), chunk_result))}")

Length of chunk list: 35
Chunk lengths: [2442, 2498, 2475, 2444, 2494, 2470, 2479, 2450, 2471, 2453, 2499, 2487, 2487, 2464, 2468, 2488, 2485, 2454, 2460, 2482, 2481, 2487, 2452, 2442, 2467, 2474, 2492, 2489, 2401, 2499, 2470, 2429, 2488, 2388, 317]


**VECTORS NORMALIZATION**

In [20]:
row_vectors = np.random.random((50, 50))
print(f"Array shape: {row_vectors.shape}", end='\n\n')
print(row_vectors)

Array shape: (50, 50)

[[0.71395498 0.98597342 0.06117661 ... 0.87636645 0.63359924 0.92423667]
 [0.09507358 0.88459612 0.82751223 ... 0.66849116 0.86123556 0.60486795]
 [0.24279599 0.99529196 0.45899813 ... 0.75227985 0.02561144 0.4009926 ]
 ...
 [0.26141672 0.1991353  0.91255568 ... 0.63875685 0.03916873 0.29501127]
 [0.92662155 0.8422958  0.34323096 ... 0.69827152 0.53924579 0.83517773]
 [0.5133955  0.59265681 0.62781872 ... 0.2795474  0.23262978 0.90813289]]


In [21]:
norm_vectors = normalize_vectors(row_vectors)
print(f"Norm vectors shape: {norm_vectors.shape}")
norm_vectors

Norm vectors shape: (50, 50)


array([[0.17064237, 0.23565749, 0.01462182, ..., 0.20946033, 0.15143654,
        0.22090179],
       [0.02184984, 0.20329815, 0.19017911, ..., 0.15363284, 0.19792942,
        0.13901094],
       [0.0634686 , 0.26017641, 0.11998538, ..., 0.19665131, 0.00669501,
        0.10482232],
       ...,
       [0.06822845, 0.05197331, 0.23817244, ..., 0.16671232, 0.01022284,
        0.07699646],
       [0.21680767, 0.19707743, 0.08030798, ..., 0.16337913, 0.12617084,
        0.19541196],
       [0.11327456, 0.13076262, 0.13852067, ..., 0.06167878, 0.05132697,
        0.20036863]], shape=(50, 50))

In [22]:
print("Average norm of vectors: ")
np.apply_along_axis(np.linalg.norm, arr = norm_vectors, axis = 1).mean().item()

Average norm of vectors: 


1.0

**VECTOR DATABASE**

In [4]:
# Create vector index and corresponding relational database withing vector db
# Creating connection to database
import os
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from systemComponents import embedding_model

DB_PASSWORD = os.getenv("DB_PASSWORD")
engine = create_engine(f"postgresql://postgres:{DB_PASSWORD}@localhost/retriever_chunk_dbs")
print(type(engine))

<class 'sqlalchemy.engine.base.Engine'>


In [6]:
vectordb = VectorDb(relational_db_engine=engine,
                    embedding_function = embedding_model,
                    tablename='test_table_chunk')

In [7]:
vectordb.create_index()

In [8]:
some_documents = [
    "Hello, my name is Luchian. Where can i find the nearest tacobell",
    "Without leverage you became desperate and it is really frightening",
    "You have to know what you are doing"
]
for stmt in some_documents:
    print(stmt) 

Hello, my name is Luchian. Where can i find the nearest tacobell
Without leverage you became desperate and it is really frightening
You have to know what you are doing


In [9]:
vectordb.load_chunks(some_documents, label=0)

Length of chunks: 3
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Loading chunks to database with batch size 3: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s]


**RETRIEVER MODULE EXTRACTION**

In [6]:
import os
import sqlalchemy
from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session, DeclarativeBase, Mapped, mapped_column

from systemComponents import embedding_model, RetrieverModule

# Creating connection to database
DB_PASSWORD = os.getenv("DB_PASSWORD")
engine = create_engine(f"postgresql://postgres:{DB_PASSWORD}@localhost/retriever_chunk_dbs")
print(type(engine))

<class 'sqlalchemy.engine.base.Engine'>


In [16]:
# Create vector database with corresponding ids
vectordb = VectorDb(relational_db_engine = engine,
                    embedding_function = embedding_model,
                    tablename = 'DOCS_CHUNK_SIZE_300')
vectordb.load_index("C:\\main\\GitHub\\documentReviewSystem\\metrics\\retriever\\EMBD_CHUNKS_OF_SIZE_1800.index")

Vector index read from the path C:\main\GitHub\documentReviewSystem\metrics\retriever\EMBD_CHUNKS_OF_SIZE_1800.index


In [20]:
retrieverModule = RetrieverModule(vector_database = vectordb, k=5)

In [21]:
result = retrieverModule.retrieve("ML and gradient boosting")
print(len(result))
result

5


[(1675,
  'Forsmalldatasets, ()observedthatusingrectifyingnon-Jarrettetal.2009\nlinearitiesisevenmoreimportantthanlearningtheweightsofthehiddenlayers.\nRandomweightsaresufficienttopropagateusefulinformationthrougharectified\nlinearnetwork,allowingtheclassifierlayeratthetoptolearnhowtomapdifferent\n',
  0),
 (2641,
  'throughasetoftdifferentchoicesofkernelstackineachdirection.Iftisequalto\ntheoutputwidth,thisisthesameasalocallyconnectedlayer.\nZi,j,k=\n\ue058\nl,m,n\nVl,jm ,kn+−1+−1Ki,l,m,n,jt ,kt%+1%+1, (9.10)\nwhereis themodulooperation,with% t%t=0(,t+1)%t=1,etc.It is\n',
  0),
 (2656,
  's.t.\n( 1) +=n−×spk\n\ue058\nq\nKq,i,m,pGq,l,n. (9.13)\nAutoencodernetworks, describedinchapter, arefeedforwardnetworks14\ntrainedtocopytheirinputtotheiroutput.AsimpleexampleisthePCAalgorithm,\n357',
  0),
 (2667,
  'recurrentnetworkiterativelyrefinesitsestimateˆYbyusingapreviousestimateofˆY\nasinputforcreatinganewestimate. Thesameparametersareusedforeachupdated\nestimate,andtheestimatecanberefinedasmanytime